<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Database\Migrations\Migrator;
use Illuminate\Support\Facades\DB;

/**
 * Production here has no shell, only phpMyAdmin - so schema changes used to be
 * hand-written .sql files that could drift from the real migrations. This prints
 * the SQL that the migrations themselves would run, plus the `migrations` table
 * bookkeeping rows, so a migration is the only place a schema change is written.
 *
 *   php artisan pmo:migration-sql                       # everything not yet applied to THIS database
 *   php artisan pmo:migration-sql --since=<migration>   # everything after that migration (use the
 *                                                         newest one production already has)
 *   php artisan pmo:migration-sql --output=database/sql/foo.sql
 */
class MigrationSql extends Command
{
    protected $signature = 'pmo:migration-sql {--since= : Name of the last migration production already has} {--output= : Write to this file instead of the screen}';

    protected $description = 'Print the SQL of pending migrations (for running in phpMyAdmin on production)';

    public function handle(Migrator $migrator): int
    {
        $files = $migrator->getMigrationFiles(array_merge($migrator->paths(), [database_path('migrations')]));
        $names = array_keys($files);
        sort($names);

        if ($since = $this->option('since')) {
            if (! in_array($since, $names, true)) {
                $this->error("ไม่พบ migration ชื่อ {$since}");

                return self::FAILURE;
            }
            $pending = array_values(array_filter($names, fn ($n) => strcmp($n, $since) > 0));
        } else {
            $repository = $migrator->getRepository();
            $pending = array_values(array_diff($names, $repository->repositoryExists() ? $repository->getRan() : []));
        }

        if (! $pending) {
            $this->info('ไม่มี migration ที่ค้างอยู่');

            return self::SUCCESS;
        }

        $connection = DB::connection();
        $grammar = $connection->getQueryGrammar();

        $sql = ['-- Avatar Electric PMO - generated by `php artisan pmo:migration-sql`', '-- Run in phpMyAdmin (SQL tab) on the production database BEFORE uploading the matching code.', '-- Back up the database first.', ''];

        foreach ($pending as $i => $name) {
            // resolvePath() is protected in the framework; it's the one that handles both
            // anonymous (`return new class`) and named migration files.
            $path = $files[$name];
            $migration = (fn () => $this->resolvePath($path))->call($migrator);

            $sql[] = "-- {$name}";

            $queries = $connection->pretend(fn () => $migration->up());

            foreach ($queries as $q) {
                $sql[] = rtrim($grammar->substituteBindingsIntoRawSql($q['query'], $connection->prepareBindings($q['bindings'])), ';').';';
            }

            // Same batch number for the whole run, like `artisan migrate` would use.
            $sql[] = $i === 0
                ? "INSERT INTO `migrations` (`migration`, `batch`) SELECT '{$name}', COALESCE(MAX(`batch`), 0) + 1 FROM `migrations`;"
                : "INSERT INTO `migrations` (`migration`, `batch`) SELECT '{$name}', MAX(`batch`) FROM `migrations`;";
            $sql[] = '';
        }

        $output = implode("\n", $sql);

        if ($path = $this->option('output')) {
            if (! is_dir(dirname($path))) {
                mkdir(dirname($path), 0775, true);
            }

            file_put_contents($path, $output);
            $this->info('เขียน SQL ของ '.count($pending)." migration ลง {$path}");
        } else {
            $this->line($output);
        }

        return self::SUCCESS;
    }
}
