-- Avatar Electric PMO - generated by `php artisan pmo:migration-sql`
-- Run in phpMyAdmin (SQL tab) on the production database BEFORE uploading the matching code.
-- Back up the database first.

-- 2026_10_05_000001_migrate_remarks_to_activity_notes

            INSERT INTO activity_logs (project_id, user_id, loggable_type, loggable_id, action, description, created_at, updated_at)
            SELECT t.id, NULL, 'App\\Models\\Project', t.id, 'remark_migrated', t.remark, '2026-10-05 09:48:45', '2026-10-05 09:48:45'
            FROM projects t
            WHERE t.remark IS NOT NULL AND t.remark <> ''
              AND NOT EXISTS (
                  SELECT 1 FROM activity_logs a
                  WHERE a.loggable_type = 'App\\Models\\Project' AND a.loggable_id = t.id AND a.action = 'remark_migrated'
              )
        ;

            INSERT INTO activity_logs (project_id, user_id, loggable_type, loggable_id, action, description, created_at, updated_at)
            SELECT t.project_id, NULL, 'App\\Models\\Cabinet', t.id, 'remark_migrated', t.remark, '2026-10-05 09:48:45', '2026-10-05 09:48:45'
            FROM cabinets t
            WHERE t.remark IS NOT NULL AND t.remark <> ''
              AND NOT EXISTS (
                  SELECT 1 FROM activity_logs a
                  WHERE a.loggable_type = 'App\\Models\\Cabinet' AND a.loggable_id = t.id AND a.action = 'remark_migrated'
              )
        ;
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_10_05_000001_migrate_remarks_to_activity_notes', COALESCE(MAX(`batch`), 0) + 1 FROM `migrations`;

-- 2026_10_05_000002_add_soft_deletes_for_trash
alter table `projects` add `deleted_at` timestamp null;
alter table `cabinets` add `deleted_at` timestamp null;
alter table `cabinet_tasks` add `deleted_at` timestamp null;
alter table `cabinet_subtasks` add `deleted_at` timestamp null;
alter table `cabinet_checklists` add `deleted_at` timestamp null;
alter table `projects` drop index `projects_project_no_unique`;
alter table `projects` add index `projects_project_no_index`(`project_no`);
alter table `cabinets` drop index `cabinets_mo_no_unique`;
alter table `cabinets` add index `cabinets_mo_no_index`(`mo_no`);
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_10_05_000002_add_soft_deletes_for_trash', MAX(`batch`) FROM `migrations`;

-- 2026_10_05_000003_create_notifications_table
create table `notifications` (`id` char(36) not null, `type` varchar(255) not null, `notifiable_type` varchar(255) not null, `notifiable_id` bigint unsigned not null, `data` text not null, `read_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null, primary key (`id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `notifications` add index `notifications_notifiable_type_notifiable_id_index`(`notifiable_type`, `notifiable_id`);
INSERT INTO `migrations` (`migration`, `batch`) SELECT '2026_10_05_000003_create_notifications_table', MAX(`batch`) FROM `migrations`;
